function write_paper_macros_empirical(cfg, stats, outTexPath)
%WRITE_PAPER_MACROS_EMPIRICAL  Write LaTeX macros for the paper.
%
% Inputs
%   cfg        : config struct from config_empirical()
%   stats      : struct of realised empirical summaries
%   outTexPath : full path to .tex file to write
%
% Expected / optional stats fields
%   stats.sampleStartLabel      e.g. 'January 1975'
%   stats.sampleEndLabel        e.g. 'January 2026'
%   stats.sampleStartYear       e.g. 1975
%   stats.sampleEndYear         e.g. 2026
%   stats.nContigStates         e.g. 48
%   stats.snapshotUsedLabel     e.g. 'Jan 1995'
%   stats.v2spread_90_10        numeric
%
%   stats.bands : cell array or struct array with fields
%       .tag
%       .lowF
%       .upF
%       .dt1sigma_med_mo
%       .dt1sigma_max_mo
%       .dt9010_med_mo
%       .dt9010_max_mo
%       .useYears

fid = fopen(outTexPath, 'w');
assert(fid > 0, 'Could not open for writing: %s', outTexPath);
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '%% Auto-generated by MATLAB (%s). DO NOT EDIT.\n', datestr(now));
fprintf(fid, '%% Source: empirical pipeline.\n\n');

% -------------------------------------------------------------------------
% Config-driven metadata macros
% -------------------------------------------------------------------------
writeMacro_(fid, 'WaveletDt', texNum_(cfg.wave.dt));
writeMacro_(fid, 'WaveletDj', texNum_(cfg.wave.dj));
writeMacro_(fid, 'WaveletMother', waveletLabel_(cfg.wave.mother));
writeMacro_(fid, 'DataSeriesLabel', char(string(cfg.data.series)));

writeMacro_(fid, 'BandLabelMain',  sprintf('%g--%gy', cfg.bands.main.lowF, cfg.bands.main.upF));
writeMacro_(fid, 'BandLabelLong',  sprintf('%g--%gy', cfg.bands.long.lowF, cfg.bands.long.upF));
writeMacro_(fid, 'BandYearsMain',  sprintf('%g--%g years', cfg.bands.main.lowF, cfg.bands.main.upF));
writeMacro_(fid, 'BandYearsLong',  sprintf('%g--%g years', cfg.bands.long.lowF, cfg.bands.long.upF));

if isfield(cfg, 'snapshot') && isfield(cfg.snapshot, 'tstar_req') && ~isempty(cfg.snapshot.tstar_req)
    writeMacro_(fid, 'SnapshotRequestedLabel', datestr(cfg.snapshot.tstar_req, 'mmm yyyy'));
end

fprintf(fid, '\n');

% -------------------------------------------------------------------------
% Realised sample / run metadata macros
% -------------------------------------------------------------------------
if isfield(stats, 'sampleStartLabel')
    writeMacro_(fid, 'SampleStartLabel', stats.sampleStartLabel);
end
if isfield(stats, 'sampleEndLabel')
    writeMacro_(fid, 'SampleEndLabel', stats.sampleEndLabel);
end
if isfield(stats, 'sampleStartYear')
    writeMacro_(fid, 'SampleStartYear', sprintf('%d', stats.sampleStartYear));
end
if isfield(stats, 'sampleEndYear')
    writeMacro_(fid, 'SampleEndYear', sprintf('%d', stats.sampleEndYear));
end
if isfield(stats, 'nContigStates')
    writeMacro_(fid, 'ContigStateCount', sprintf('%d', stats.nContigStates));
end
if isfield(stats, 'snapshotUsedLabel')
    writeMacro_(fid, 'SnapshotUsedLabel', stats.snapshotUsedLabel);
end
if isfield(stats, 'v2spread_90_10')
    writeMacro_(fid, 'VTwoSpreadNinetyTen', sprintf('%.2f', stats.v2spread_90_10));
end

fprintf(fid, '\n');

% -------------------------------------------------------------------------
% Band-specific empirical macros
% -------------------------------------------------------------------------
if isfield(stats, 'bands') && ~isempty(stats.bands)
    bands = stats.bands;
    if iscell(bands)
        bands = [bands{:}];
    end

    for k = 1:numel(bands)
        b = bands(k);

        suf = bandSuffix_(b.lowF, b.upF);
        bandLabel = sprintf('%g--%gy', b.lowF, b.upF);

        if b.useYears
            med1 = sprintf('%.2f', b.dt1sigma_med_mo / 12);
            max1 = sprintf('%.2f', b.dt1sigma_max_mo / 12);
            med9 = sprintf('%.2f', b.dt9010_med_mo / 12);
            max9 = sprintf('%.2f', b.dt9010_max_mo / 12);
            unit = 'years';
        else
            med1 = sprintf('%.2f', b.dt1sigma_med_mo);
            max1 = sprintf('%.2f', b.dt1sigma_max_mo);
            med9 = sprintf('%.2f', b.dt9010_med_mo);
            max9 = sprintf('%.2f', b.dt9010_max_mo);
            unit = 'months';
        end

        fprintf(fid, '%% Band %s (%g--%gy); reported units: %s\n', ...
            b.tag, b.lowF, b.upF, unit);

        writeMacro_(fid, ['BandLabel' suf], bandLabel);
        writeMacro_(fid, ['LagUnits' suf], unit);

        writeMacro_(fid, ['LagOneSigmaMedian' suf], med1);
        writeMacro_(fid, ['LagOneSigmaMax' suf], max1);
        writeMacro_(fid, ['LagNinetyTenMedian' suf], med9);
        writeMacro_(fid, ['LagNinetyTenMax' suf], max9);

        fprintf(fid, '\n');
    end
end

end

% =========================================================================
function writeMacro_(fid, name, value)
fprintf(fid, '\\newcommand{\\%s}{%s}\n', name, value);
end

% =========================================================================
function s = texNum_(x)
% Prefer simple exact fractions where appropriate
if abs(x - 1/12) < 1e-12
    s = '1/12';
elseif abs(x - 1/30) < 1e-12
    s = '1/30';
else
    s = sprintf('%.6g', x);
end
end

% =========================================================================
function s = waveletLabel_(mother)
mother = char(string(mother));
switch lower(mother)
    case 'morlet'
        s = 'complex Morlet';
    otherwise
        s = mother;
end
end

% =========================================================================
function suf = bandSuffix_(lowF, upF)
% e.g. 8-10 -> EightTen ; 11-14 -> ElevenFourteen
suf = [numWord_(lowF) numWord_(upF)];
end

% =========================================================================
function w = numWord_(n)
map = containers.Map( ...
    num2cell(0:20), ...
    {'Zero','One','Two','Three','Four','Five','Six','Seven','Eight','Nine', ...
     'Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen', ...
     'Seventeen','Eighteen','Nineteen','Twenty'});

assert(isKey(map, n), 'numWord_: add mapping for n=%g', n);
w = map(n);
end